import NavBar from './components/navbar'
import './globals.css'

export const metadata = {
  title: 'panaverse website',
  description: 'Generated by afzal peter',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-500 text-gray-200 font-sans'>
<NavBar />
        {children}
      </body>
    </html>
  )
}
